name: convert-marp

on:
  push:
    branches:
      - master
      - develop
      - works/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Container
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d --build
      - name: Convert md files
        run: |
          cd .devcontainer 
          docker-compose exec -T marp npx @marp-team/marp-cli@latest -I contents/ -o contents/html --theme-set $(find themes | grep .css) -y 
      - name: Upload HTML Slides
        uses: actions/upload-artifact@v2
        with:
          name: html-slide
          path: contents/html
      - name: Convert md files
        run: |
          ls -a
          docker run --rm --init -e MARP_USER="$(id -u):$(id -g)"  -v $PWD:/home/marp/app  marpteam/marp-cli -I contents/ -o contents/html --theme-set $(find themes | grep .css) --pdf