name: convert-marp

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Container
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d --build
      - name: Convert md files.
        run: |
          cd .devcontainer 
          docker-compose exec -T marp npx @marp-team/marp-cli@latest contents/*.md -y