name: convert-marp

on:
  push:
    branches:
      - master
      - develop
      - works/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Container
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d --build
      - name: Convert md to html
        run: |
          cd .devcontainer 
          docker run --rm --init --env-file .devcontainer/.env -e MARP_USER="$(id -u):$(id -g)" -v $PWD:/home/marp/app  marpteam/marp-cli -I contents/ -o contents/html --theme-set $(find themes | grep .css)
      - name: Upload HTML Slides
        uses: actions/upload-artifact@v2
        with:
          name: html-slide
          path: contents/html
      - name: Convert md to pdf
        run: |
          pwd
          docker run --rm --init --env-file .devcontainer/.env -e MARP_USER="$(id -u):$(id -g)" -v $PWD:/home/marp/app  marpteam/marp-cli -I contents/ -o contents/pdf --theme-set $(find themes | grep .css) --pdf
      - name: Upload pdf Slides
        uses: actions/upload-artifact@v2
        with:
          name: pdf-slide
          path: contents/pdf
      - name: Convert md to pptx
        run: |
          ls -a
          docker run --rm --init --env-file .devcontainer/.env -e MARP_USER="$(id -u):$(id -g)" -v $PWD:/home/marp/app  marpteam/marp-cli -I contents/ -o contents/pptx --theme-set $(find themes | grep .css) --pptx
      - name: Upload pptx Slides
        uses: actions/upload-artifact@v2
        with:
          name: pptx-slide
          path: contents/pptx