name: convert-marp

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetUp Container
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d --build
      - name: Convert md files
        run: |
          cd .devcontainer 
          docker-compose exec -T marp npx @marp-team/marp-cli@latest -I contents/ -o contents/html -y
          docker-compose exec -T marp npx @marp-team/marp-cli@latest -I contents/ -o contents/pdf -y --pdf
          docker-compose exec -T marp npx @marp-team/marp-cli@latest -I contents/ -o contents/pptx -y --pptx
      - name: Upload Slides
        uses: actions/upload-artifact@v2
        with:
          name: pdf slide
          path: content/pdf